### ISSUE TITLE
Unable to install VS2019

### ISSUE THREAD

**Issue by bstriche** [solvsoftware/SSDT-Continuous-Deployment-Project-Template#2]
When attempting to install the extension in VS2019, I am seeing the following error:

> The extension with ID 'SSDT_CD_Project.625944c8-c903-44d8-82ae-888398c19a53' is not installed to Microsoft Visual Studio Enterprise 2019.
> Extension cannot be installed to the following products due to missing prerequisites:
> 	Microsoft Visual Studio Enterprise 2019
> 		-------------------------------------------------------
> 		Identifier   : Microsoft.VisualStudio.Component.SQL.CMDUtils
> 		Name         : SQL Server 2012 Command Line Utilities
> 		Version      : [15.0.25824.0,17.0)
> 		Error        : The prerequisite specified does not exist

I was able to install the extension without issue in VS2017 on the same machine.

**Comment by stephen-ve** [comment]
Same issue here

**Comment by jimlester** [comment]
Me too.
