### ISSUE TITLE
Support for VS 2022?

### ISSUE THREAD

**Issue by pipbrandy** [solvsoftware/SSDT-Continuous-Deployment-Project-Template#3]
Hello,

Is this still an active project?  I notice that it will install on VS 2017 & 2019.  Will it support VS 2022?

Also, I'm new to the use of MERGE queries.  I see you reference the work of Daniel Nolan.  I notice that he has a repo here for an "sp_generate_merge" script:  https://github.com/readyroll/generate-sql-merge.

A question I have is whose work is most up to date, especially for use in Azure DB.  Daniel's has more recent updates.  Would his be more safe to use, cover more possible errors, etc.?

Thanks!

**Comment by RadoslavGatev** [comment]
Hi,

I've just updated it to support VS 2022 - https://marketplace.visualstudio.com/items?itemName=SolvSoftware.SSDT-Continuous-Deployment-Project-Template

The latest version of sp_generate_merge has been copied as well. The latest updates were not major changes and the stored procedure seems to work well (I tested with SQL Server 2022).

**Comment by pipbrandy** [comment]
Oh wow, thanks.  I had completely forgotten about this!  Thanks for fixing.

That sp_generate_merge  procedure (the old one, haven't looked at the new one) would miss one closing parenthesis (it's easy to correct in the generated script).  Where you able to fix that?

Thanks!

**Comment by RadoslavGatev** [comment]
I haven't had any problems with missing parenthesis, to be honest. I've tried the new version against several tables from AdventureWorks and it worked just fine. The logging in the new version is even improved.
